### ISSUE TITLE
Compatible with vertical bar

### ISSUE THREAD

**Issue by Linh1706** [hedayaty/NetSpeed#115]
Hi, 
I use Dash to Panel extension to move the topbar to the side. 
then this extension is not display correctly on a 32px vertical bar.
if you could please make it compatible with vertical bar.
![Screenshot from 2020-03-10 23-07-43](https://user-images.githubusercontent.com/22808510/76333678-8afc8980-6324-11ea-8860-c8cf092c3206.png)

Thanks

**Comment by hedayaty** [comment]
That requires too much work.
Unfortunately, I can not do this for now
