### ISSUE TITLE
please support gnome 3.36

### ISSUE THREAD

**Issue by ghost** [hedayaty/NetSpeed#117]

**Comment by ebeem** [comment]
the extension is functional in gnome 3.36
what is the problem you're facing?

**Comment by ydsjqt** [comment]
it`s ok  sorry

ebeem <notifications@github.com> 于2020年4月12日周日 下午1:22写道：

**Comment by wuyuansushen** [comment]
> the extension is functional in gnome 3.36
> what is the problem you're facing?

Sorry, I can not find this in Fedora Software......I am using Gnome 3.36.1

**Comment by wayne9499** [comment]
same, after upgrading `ubuntu 20.04` to `ubuntu 20.10` its just vanished.. can't find it in the **Ubuntu Software**

**Comment by YalandHong** [comment]
> same, after upgrading `ubuntu 20.04` to `ubuntu 20.10` its just vanished.. can't find it in the **Ubuntu Software**

I didn't find it in Ubuntu App Store. I installed it from the **official website for Gnome Extensions**, following this article:
http://ubuntuhandbook.org/index.php/2020/06/download-upload-speed-ubuntu-20-04-panel/

**Comment by hedayaty** [comment]
Thanks for respond and help.
I felt the article is true to extension.
