### ISSUE TITLE
Support for Ubuntu 20.04 LTS (gnome 3.36)

### ISSUE THREAD

**Issue by PriyanshuMay** [hedayaty/NetSpeed#120]
* Couldn't install the widget directly from the software centre as I used to do in the earlier 18.04.
* Even after installing the extension from gnome's website , couldn't locate the package in installed apps in any gui package manager and had to visit gnome's extension website to change some settings

**Comment by avil25** [comment]
The Extention support has been removed from the software center and the only way is to install it from extensions.gnome.org.
ubuntu/gnome 3.36 comes with Extention app in with you can manage your installed extensions. You can access the setting from this app. 

![Screenshot from 2020-05-01 19-35-14](https://user-images.githubusercontent.com/40562410/80811193-01aa5a80-8be3-11ea-961f-f1bc0f5bc2fc.png)

**Comment by PriyanshuMay** [comment]
Ok. Thank you for clarifying.
