### ISSUE TITLE
Reposition

### ISSUE THREAD

**Issue by larrryfisherthefisherman** [hedayaty/NetSpeed#125]
How can I reposition this extension to the left side of my icons? I was looking at the source code of the exentsion but I can't seem to figure it out and its not in the perferences.

I want it to be on the left with my other extensions...

So for that to happen I believe I need it to prefer "center"

https://i.imgur.com/9jirVVj.png

Thanks in advance.

**Comment by hedayaty** [comment]
Next version should have this.
Note, you need to reload the extension (or login/logout) to setting to work :(
