### ISSUE TITLE
Having problem in installing

### ISSUE THREAD

**Issue by MHDSDT** [hedayaty/NetSpeed#126]
I just extract the files to ~/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com. And also run "make install" and "make enable" in the terminal. And then I restarted the shell. But when I went to the tweaks, I saw this error:

GLib.FileError: Failed to open file “/home/mhdsdt/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  @/home/mhdsdt/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:34:46
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

What should I do?

**Comment by hedayaty** [comment]
I think I fiex them both
We needed to say this is supported on gnome 40 (every release I had to update the version file)
Also, some minor library change :(
