### ISSUE TITLE
make enable issue

### ISSUE THREAD

**Issue by LukasHaefele** [hedayaty/NetSpeed#129]
On executing make enable the terminal gives the error "Extension “netspeed@hedayaty.gmail.com” does not exist".

I'm on Pop!_OS 20.04 (so basically Ubuntu)

**Comment by demolg** [comment]
You are mostly on wayland. Re-login and run command again or enable it in `Extensions` app.

**Comment by muhammadyusuf-kurbonov** [comment]
try to execute make commands with sudo. It helped me

**Comment by c84c** [comment]
To use `make enable` the first time you must:
1.  `make install`
2. reload gnome-shell: on X11 press `Alt+F2` then  type `r` or `restart`, on wayland re-login. This step is necessary on every code change
3. `make enable`

**Comment by hedayaty** [comment]
Sorry gnome reload is not the same anymore :(
What @c84c said is probably the best advice.

DO NOT use sudo.
