### ISSUE TITLE
Support for ubuntu 22

### ISSUE THREAD

**Issue by imkonsowa** [hedayaty/NetSpeed#149]
Hey, thanks for the awesome extension, Are you going to support the latest Ubuntu LTS 22 soon?

**Comment by kushan-gunasekera** [comment]
**The extension is incompatible with the current GNOME version**

![image](https://user-images.githubusercontent.com/20010279/164555950-dbb4543b-21d4-42e1-8ef2-297e8f4a54a8.png)

**Comment by abbyck** [comment]
Source has been updated to run on GNOME 42 btw. You can build from source to get it working till the changes propagate to extenstions.gnome

**Comment by hedayaty** [comment]
I have submitted this a while ago.
They have some complaints about the user of timer. + some ask for use the next new class format.
I explained the timer thing. They have not responded.

**Comment by hedayaty** [comment]
Until we here from the extensions team. You can build from source.
