### ISSUE TITLE
Gnome 42 / Ubuntu 22 support needs release (workaround provided)

### ISSUE THREAD

**Issue by mikehardy** [hedayaty/NetSpeed#150]
I left a comment for other users on the Gnome extensions site for this one, but until there is a release of #148 you have to manually add support for gnome 42:

- `vi .local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/metadata.json`
- add `, 42` to the array of supported versions
- logout/login (so the metadata is reloaded, that happens during your login)
- you may need to re-enable it using the "extensions" applet (which itself may have problems with Wayland according to it's reviews, I dunno I use old school X still...)

Hope this helps others, thanks for the applet @hedayaty :-)

**Comment by erfantkerfan** [comment]
+1

**Comment by WatchDogsDev** [comment]
+1

**Comment by chenyhd** [comment]
If you wanna build from the source code, please check #151

**Comment by irkreja** [comment]
Adding ```,"42.2"``` worked for me

**Comment by hedayaty** [comment]
this is done by other people

**Comment by hedayaty** [comment]
#162  did the same
