### ISSUE TITLE
change icon depending on active interface and network status

### ISSUE THREAD

**Issue by denispr** [hedayaty/NetSpeed#23]
Hello,
It would be nice if the icon on right of throughput display changed, depending on the type of active interface for default route (either wireless, wired ethernet, or ppp) and the network status (active or not), like it was in Gnome 2 netspeed applet (and is still in Mate netspeed applet). The latter would be most useful to know at first sight if the network is active or not.
Thanks,
Denis

**Comment by hedayaty** [comment]
Hmm.  You can always change the device by selecting from menu (Not obvious) or from preferences.
However, in that case the bandwidth regarding that particular device will be displayed.

Generally, correctly identifying the default device is not easy. The way network-manger does the set up, your default-gateway might be accessible through multiple interfaces with different weights.

Again, that can be addressed, or I can see who is using maximum bandwidth or see how network-manager-applet or original net-speed works.

**Comment by hedayaty** [comment]
I wanted to comment that it is not a good idea; however, writing that comment made me think maybe it can be done. I can add an option to follow the default device(somehow defined).

**Comment by denispr** [comment]
Thanks for your answer, I was not aware that identifying the default device might be difficult.
The kind of network configuration I use always lets me know the default device, just typing "route -e".

If detecting the default device is more difficult in some cases, just displaying an unplugged network icon when the selected from menu network interface is down would be already great.

**Comment by hedayaty** [comment]
I think in previous update I have implemented this.
You can select "Default Gateway" as device in prefs.
My default gw does not change much so I do not notice if there are bugs.
Raise an issue if such a thing happens.

**Comment by denispr** [comment]
Thanks, I'll let you know if I notice some bug.
