### ISSUE TITLE
Gnome 3.14.1 support required

### ISSUE THREAD

**Issue by MinaCora** [hedayaty/NetSpeed#30]
Dear developer,

I ask you to enhance the extension you have developed to be compatible also with Gnome 3.14.1. 

I really love this one - because it gives a practical overview on the network connection. 

I an really looking forward to use your precisious plugin further on. 

Thanks in advance!

**Comment by MinaCora** [comment]
After installation the Gnome Tweak tools say:
__________________________________________________________________
GLib.FileError: Datei »/home/minacora/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/gschemas.compiled« konnte nicht geöffnet werden: open() ist gescheitert: Datei oder Verzeichnis nicht gefunden

Stack trace:
  @/home/minacora/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:31
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:80
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1
____________________________________________________________________
Maybe this helps.

**Comment by hedayaty** [comment]
I am working on add 3.16 + another feature.
I was mostly occupied with my daily work. I hope to make it work soon.

Thanks for feedback.

**Comment by birdofprey** [comment]
GLib.FileError: 打开文件“/home/birdofprey/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/gschemas.compiled”失败：open() 失败：没有那个文件或目录

Stack trace:
  @/home/birdofprey/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:31
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:80
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1

**Comment by hedayaty** [comment]
@birdofprey I wish you created a different issue for this.
Not sure, if this is reproducible for other people.

**Comment by birdofprey** [comment]
sorry

At 2015-10-12 02:29:20, "Amir Hedayaty" <notifications@github.com> wrote:


@birdofprey I wish you created a different issue for this.
Not sure, if this is reproducible for other people.
