### ISSUE TITLE
Fonts to big on retina screen

### ISSUE THREAD

**Issue by da-anton** [hedayaty/NetSpeed#36]
Using this plugin on a retina screen only shows three dots (...) as up/download. The fonts seem to be too big. You can see this here:

![screenshot from 2015-09-05 12-49-12](https://cloud.githubusercontent.com/assets/14137494/9698912/90bd206c-53cc-11e5-980c-19cd7ffc9889.png)

**Comment by hedayaty** [comment]
You can go to preferences, either from pop-menu on extension or firefox plug-in or gnome-tweak-tool
and from there you can increase the label sizes.
