### ISSUE TITLE
[FEATURE REQUEST] Change units

### ISSUE THREAD

**Issue by simonbcn** [hedayaty/NetSpeed#39]
It would be great if it could change the speed units.
:+1:

**Comment by hedayaty** [comment]
It does change them according to the speed.
Do you mean some sort of configuration to statically define them?

**Comment by simonbcn** [comment]
I refer to can change the units to bits/s instead Bytes/s.

**Comment by t3kg33k** [comment]
I agree. It would be nice to have the option to change the units, to reflect the same from speedtest-cli. My output from speedtest-cli:

---
Testing download speed........................................
Download: 110.83 Mbit/s
Testing upload speed..................................................
Upload: 11.51 Mbit/s

Really cool extension for sure, though.

**Comment by simonbcn** [comment]
The proper way to do this would be to add a new option in preferences.
The change is easy in the net_speed.js, it's a bit more complicated the change in preferences.

I have modified the file to use only bps:
```Diff
--- /tmp/a/net_speed.js	2016-02-12 20:13:58.053643946 +0100
+++ /tmp/b/net_speed.js	2016-02-12 20:14:23.744901255 +0100
@@ -100,21 +100,22 @@
     _speed_to_string: function(amount, digits)
     {
         if (amount == 0)
-            return { text: "0", unit: _("B/s") };
+            return { text: "0", unit: _("bps") };
         if (digits < 3)
             digits = 3;
-        amount *= 1000;
+        amount *= 8; // pasamos bytes/s a bps
+        amount *= 1000; 
+
         let unit = 0;
-        while (amount >= 1000 && unit < 3) { // 1M=1024K, 1MB/s=1000MB/s
+        while (amount >= 1000 && unit < 3) { 
             amount /= 1000;
             ++unit;
         }
-
         if (amount >= 100)
             digits -= 2;
         else if (amount >= 10)
             digits -= 1;
-        let speed_map = [_("B/s"), _("KB/s"), _("MB/s"), _("GB/s")];
+        let speed_map = [_("bps"), _("Kbps"), _("Mbps"), _("Gbps")];
         return {
             text: amount.toFixed(digits - 1),
             unit: speed_map[unit]
```

**Comment by terrycloth** [comment]
Bits-per-second arguably makes more sense anyway, since internet service providers typically rate their speeds in bits rather than bytes. At least, every ISP _I've_ ever dealt with has.

**Comment by tx44** [comment]
I'd love to see this implemented, we network engineers don't really do bytes...

**Comment by simonbcn** [comment]
I think this was implemented, no? One of the modes shows the units in `bps`.

**Comment by tx44** [comment]
Not for me... just installed the extension from https://extensions.gnome.org/extension/104/netspeed/ and its only giving bytes

**Comment by simonbcn** [comment]
Sorry, I was mistaken for another extension. :blush:

**Comment by hedayaty** [comment]
Thanks @l3nn4rt took care of this.
