### ISSUE TITLE
Update for Gnome 3.20

### ISSUE THREAD

**Issue by BoBeR182** [hedayaty/NetSpeed#42]
Please update the extension to be compatible with Gnome version 3.20

**Comment by nmaggioni** [comment]
+ :100:

**Comment by WeissJT** [comment]
After adding the new version in metadata shows this error:

GLib.FileError: Failed to open file '/home/weissjt/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  @/home/weissjt/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:31
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:238
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:376
  @<main>:1

**Comment by terrycloth** [comment]
GNOME 3.22 should be the last major release where this is necessary: The API has apparently stabilized enough that they decided to [disable the compatibility check](https://git.gnome.org/browse/gnome-shell/commit?id=5e0e3edc7be44c9e370604f1d3514efc37e68a94).

**Comment by BoBeR182** [comment]
I assume this will be closed once the 3.22 support is set up?

**Comment by hedayaty** [comment]
@terrycloth it seems like a change in shell not the extension right?
I noticed that are some js errors which surface on 3.24.

**Comment by terrycloth** [comment]
My comment was specifically about GNOME Shell no longer requiring extensions to explicitly list compatible Shell versions, as of GNOME 3.24. I don't know about any specific JavaScript errors the extension might have in GNOME 3.24 --- perhaps they made some change to the API after all? Depends on the error I guess.

**Comment by terrycloth** [comment]
I think this issue should be resolved, as of commit bd2dbecd57. Right? The latest from GNOME Software seems to work as expected.

**Comment by hedayaty** [comment]
I assume this is taken care of.
@terrycloth I want to close, this.
Since, you are helping me this repo so much, I want to make sure I am not missing anything

**Comment by terrycloth** [comment]
I didn't open this issue, so I can't close it. However, I'm pretty sure NetSpeed should be compatible with the latest GNOME Shell by now, which is what this issue was about.

**Comment by BoBeR182** [comment]
Seems fixed, closing issue.
