### ISSUE TITLE
please add GNU GENERAL PUBLIC LICENSE file

### ISSUE THREAD

**Issue by martinkg** [hedayaty/NetSpeed#50]
please add GNU GENERAL PUBLIC LICENSE file from
https://www.gnu.org/licenses/gpl-3.0.de.html

**Comment by terrycloth** [comment]
Or, if you prefer, it's also available in [plain text](https://www.gnu.org/licenses/gpl-3.0.txt) and [Markdown](https://www.gnu.org/licenses/gpl-3.0.md)

**Comment by hedayaty** [comment]
Added gpl2
