### ISSUE TITLE
Settings widget still shows English text when system is configured to use other locales

### ISSUE THREAD

**Issue by terrycloth** [hedayaty/NetSpeed#55]
Today, I installed NetSpeed from extensions.gnome.org. I opened GNOME Settings > Region & Language, and changed Language from English to German. I logged out of GNOME Shell, and logged back in. Throughout GNOME Shell, all text labels were in German, but the NetSpeed settings menu still used English for all text labels. I also tried this with French, but with the same results --- French used throughout the shell, but not for the NetSpeed settings.

I'm using the latest version of NetSpeed from the extensions website, with GNOME 3.22, on Fedora 25 Workstation x86_64.

Let me know if I can provide any other debugging information to help figure out this issue.

**Comment by martinkg** [comment]
problem fixed by attached patch.
[fix_gettext-domain.patch.txt](https://github.com/hedayaty/NetSpeed/files/854197/fix_gettext-domain.patch.txt)

**Comment by hedayaty** [comment]
@martinkg people have sent very similar pull-request.
I also added yours on the schema file.
