### ISSUE TITLE
failed to open file  (schemas/gschemas.compiled not found)

### ISSUE THREAD

**Issue by martinkg** [hedayaty/NetSpeed#56]
GLib.FileError: Failed to open file '/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  @/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:31
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1

Fedora 25
GNOME Shell 3.22.2

**Comment by terrycloth** [comment]
To clarify, we're trying to package your extension as an RPM for Fedora. Usually we *move* the `.gschema.xml` file to the global directory, `/usr/share/glib-2.0/schemas/`, recompile all schemas there with the `glib-compile-schemas` command, and *omit* the precompiled `gschemas.compiled` file. I've successfully done this for several other GNOME Shell extensions, and they all detect the schemas in the new location. However, after installing the NetSpeed RPM, GNOME Tweak Tool shows the above error message when you click on the settings button for NetSpeed. And the switch to enable or disable the extension is grayed out.

Here's the error message with the original formatting preserved:

```
GLib.FileError: Failed to open file '/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  @/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:31
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
```

Here are the files owned by the RPM after installation:

* `/usr/share/doc/gnome-shell-extension-netspeed/`
* `/usr/share/doc/gnome-shell-extension-netspeed/CHANGELOG`
* `/usr/share/doc/gnome-shell-extension-netspeed/README`
* `/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.netspeed.gschema.xml`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/extension.js`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/layout_menu_item.js`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/metadata.json`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/net_speed_status_icon.js`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/net_speed.js`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js`
* `/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/stylesheet.css`
* `/usr/share/licenses/gnome-shell-extension-netspeed/`
* `/usr/share/licenses/gnome-shell-extension-netspeed/LICENSE`
* `/usr/share/locale/de/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/en_CA/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/fa/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/fr/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/it/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/pt_BR/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/zh_CN/LC_MESSAGES/netspeed.mo`
* `/usr/share/locale/zh_TW/LC_MESSAGES/netspeed.mo`

...Does NetSpeed use a hard-coded gschema path or something?

**Comment by jenslody** [comment]
I also answered in Fedoras devel mailinglist.
The following patch fixes the issue and should work with local and global build, by first searching for the existence of the local path and using it, if it exists, otherwise it uses the global default path:

``` diff
--- a/prefs.js	2017-03-28 22:42:21.070687232 +0200
+++ b/prefs.js	2017-03-28 22:42:34.680952138 +0200
@@ -27,8 +27,10 @@
 const NetworkManager = imports.gi.NetworkManager;
 const _ = Gettext.domain('netspeed').gettext;
 
-let schemaDir = Extension.dir.get_child('schemas').get_path();
-let schemaSource = Gio.SettingsSchemaSource.new_from_directory(schemaDir, Gio.SettingsSchemaSource.get_default(), false);
+let schemaDir = Extension.dir.get_child('schemas');
+let schemaSource = schemaDir.query_exists(null)?
+                    Gio.SettingsSchemaSource.new_from_directory(schemaDir.get_path(), Gio.SettingsSchemaSource.get_default(), false):
+                    Gio.SettingsSchemaSource.get_default();
 let schema = schemaSource.lookup('org.gnome.shell.extensions.netspeed', false);
 let Schema = new Gio.Settings({ settings_schema: schema });
 
--- a/net_speed.js	2017-03-28 22:50:13.212931817 +0200
+++ b/net_speed.js	2017-03-28 22:50:57.355800047 +0200
@@ -302,12 +302,10 @@
         this._devices = new Array();
         this._client = NMC.Client.new();
 
-        let schemaDir = Extension.dir.get_child('schemas').get_path();
-        let schemaSource = Gio.SettingsSchemaSource.new_from_directory(
-            schemaDir,
-            Gio.SettingsSchemaSource.get_default(),
-            false
-        );
+        let schemaDir = Extension.dir.get_child('schemas');
+        let schemaSource = schemaDir.query_exists(null)?
+                            Gio.SettingsSchemaSource.new_from_directory(schemaDir.get_path(), Gio.SettingsSchemaSource.get_default(), false):
+                            Gio.SettingsSchemaSource.get_default();
         let schema = schemaSource.lookup('org.gnome.shell.extensions.netspeed', false);
         this._setting = new Gio.Settings({ settings_schema: schema });
         this._saving = 0;
```

**Comment by hedayaty** [comment]
@jenslody looks good to me.
If you create a pull-request, I can merge it.

**Comment by jenslody** [comment]
Done.
