### ISSUE TITLE
Can't get it to work on Gnome-shell 3.24 (Ubuntu Zesty)

### ISSUE THREAD

**Issue by drivera73** [hedayaty/NetSpeed#61]
The extension was working fine with previous versions, but after the update to Zesty the extensions website (https://extensions.gnome.org/extension/104/netspeed/) will only show "ERROR".  On a different computer with a fresh install, the extension will be downloaded but not activated, but no error is reported - it simply flicks back to "off".

No error is reported via Looking Glass that I've been able to find (new to debugging Gnome Shell extensions, so probably not looking in the right place).

**Comment by maweki** [comment]
You can try to look into `journalctl --user` if you have journald (don't know whether this is ubuntu standard). There you could find additional error messages.

**Comment by drmikecrowe** [comment]
GsPluginShellExtensions no app for changed netspeed@hedayaty.gmail.com

**Comment by timoschwarzer** [comment]
Fixed with https://github.com/hedayaty/NetSpeed/pull/62
