### ISSUE TITLE
Extension makes top-right menu displayed in english, not current locale

### ISSUE THREAD

**Issue by julieni** [hedayaty/NetSpeed#65]
Hi,
when the extension is enabled, the menu (audio, network, vpn, user, lock, logout, ...) is displayed in english, not current locale (french for me).

**Comment by hedayaty** [comment]
I think I do not quiet get what you mean.
I am using translations by some nice french person; if a part is missing, could you send me a screen-shot?

**Comment by julieni** [comment]
When the extension is not enabled, I have the gnome dropdown on the right (don't know how to call it) in French, all is OK: 
https://www.issler.net/netspeed-65-disabled.png

When I enable the extension and restart the shell, that dropdown menu is in English:
https://www.issler.net/netspeed-65-enabled.png

Thanks

**Comment by hedayaty** [comment]
Wow! I see.
How did I do this!

**Comment by julieni** [comment]
I think it may be related to:
https://github.com/hedayaty/NetSpeed/commit/accbff615ad7f3d165ace6cde46e58bac05b9487
