### ISSUE TITLE
When netspeed is activated, GNOME-Shell locale switches to English

### ISSUE THREAD

**Issue by vasyugan** [hedayaty/NetSpeed#75]
This is about all I can report: With netspeed enabled, the locale of the entire shell reproducibly switches to English. My default locale is de_DE. UTF-8

**Comment by hedayaty** [comment]
Do you have the latest version?
I think a similar bug was fixed recently

**Comment by hedayaty** [comment]
https://github.com/hedayaty/NetSpeed/issues/55

**Comment by vasyugan** [comment]
Yes, seems fixed now. Thanks!!
