### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by rypz79** [hedayaty/NetSpeed#76]
Hi,

Very useful extension here are some improvement suggestions:

1. When you want to monitor both up&down stream there have to be a gap between their labels in order to show all digits and units. The minimum requirement for me to see all digits and units is 37 label size, 32 unit label size (see pics with 35 and 24 respectively) it's not pretty nor stylish and takes a lot of space in my tray bar. The way to solve this is to have the option to put them one on top of the other (vertical display) instead of side by side (horizontal display)

2. Another thing that is missing is the option to choose the between constant unit measurement (B/s ,KB/s MB/s , Kb/s ,Mb/s are the most common) and changing one (the current default) which changes with speed increasement  

3. The spacing in menu label is bad even at 100 pixels size

4. Another nice option is to select the arrow icons from some given options. 

Thanks

![121](https://user-images.githubusercontent.com/28814757/41198564-002a1a9a-6c89-11e8-940a-30f2b81b5833.png)

![223](https://user-images.githubusercontent.com/28814757/41198565-0599c322-6c89-11e8-87cf-ff0218b507b8.png)

![334](https://user-images.githubusercontent.com/28814757/41198566-09a351f4-6c89-11e8-954e-077c9f0fc32a.png)

**Comment by hedayaty** [comment]
Thanks for the suggestions. (and sorry for responding with so much lag!)
1. The style! Not my strength. I am a backend guy.
But I did not like the vertical alignment, there was even a PR (I tried it)
It makes the whole top-bar taller.

2. That's a good idea. Next round of changes, I will include it.

3. Not sure, for me it does not look like that at all. They look like a clean table.
I assume nobody would be bothered if the menu is a little bit wide.

4. At some point in past, it used to be like that!
I changed it(maybe picking the portions from the PR with vertical placement) to be unicode characters.
This way it saves a little bit of space.
