### ISSUE TITLE
Got error and NetSpeed not displaying

### ISSUE THREAD

**Issue by moojek** [hedayaty/NetSpeed#77]
![screenshot from 2018-08-07 22-17-45](https://user-images.githubusercontent.com/42188458/43800332-4a690bc2-9a90-11e8-9a8e-ef470fc46acc.png)
I get this and netspeed is not shown on my tray. Any clues what might be reason?

**Comment by hedayaty** [comment]
It might be a bug which is solved.
At least, if you could provide the gnome version, the distro, and the extension version it would help.
If you are a little power user, I can help you find the error message. That way it might be even easier to fix.

**Comment by moojek** [comment]
Hey, sorry for making problem, it is working again now :smile:. Either way thank you for your effort! :heart:

**Comment by jethar** [comment]
I am getting this error on Ubuntu 19.04 with gnome shell version - GNOME Shell 3.32.1

Can you please help how to debug the issue. Is there some apt poackage which needs to be installed as pre-requisite. It was working on Ubuntu 18.10, but after upgrade is giving the error.

**Comment by fedelibre** [comment]
@jethar Perhaps you have the extension installed already? I see the  ERROR on the extension website only when the extension is installed already from my distro repository.

**Comment by fedelibre** [comment]
I had to close the session for the uninstallation of the extension to take effect. Then the ERROR message on the website disappeared and I could switch on the extension.

See this [gnome-shell issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2513) for a discussion about the restart action.
