### ISSUE TITLE
g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

### ISSUE THREAD

**Issue by martinkg** [hedayaty/NetSpeed#81]
Hi,

I'm already working with Fedora 29 in a VMWare and would like use the package
gnome-shell-extension-netspeed
I am the package maintainer of gnome-shell-extension-netspeed [1]

Can somebody have a look on this package what's going wrong here.
I do not need to ask updstream, because I can not answer.

When i run the settings, the following message appears:

$ gnome-tweaks
(gnome-shell-extension-prefs:85491): GLib-GObject-CRITICAL **: 13:24:32.585:
g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed

[1] https://koji.fedoraproject.org/koji/packageinfo?packageID=26429

Thanks
Martin

**Comment by hedayaty** [comment]
I do not quiet get what you are asking!
I am using FC29. I do not see any issue.

**Comment by martinkg** [comment]
I have installed this package on F29:
gnome-shell-extension-netspeed-3.28-0.5.20180210gite3cea60.fc29.noarch

when starting gnome-tweaks and selecting settings
![gnome tweaks_001](https://user-images.githubusercontent.com/2564124/47206729-a9599200-d389-11e8-83a6-eabe3c91a317.png)

i get this error message:
![gnome tweaks_002](https://user-images.githubusercontent.com/2564124/47206819-e4f45c00-d389-11e8-8f5b-515baa1a6dbd.png)

SyntaxError: missing ( after for

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43

**Comment by martinkg** [comment]
I have solved this issue, by copying the extension files into the local folder:
/home/martin/.local/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/schemas/

-rw-rw-r--. 1 martin martin  680  5. Feb 2018  gschemas.compiled
-rw-rw-r--. 1 martin martin 1938  5. Feb 2018  org.gnome.shell.extensions.netspeed.gschema.xml

see bugzilla report:
[Can no longer make gnome-shell extensions globally accessable.](https://bugzilla.redhat.com/show_bug.cgi?id=1565452)
