### ISSUE TITLE
missing different menu languages

### ISSUE THREAD

**Issue by martinkg** [hedayaty/NetSpeed#83]
different menu languages are not available, these are not created by the Makefile.
these are considered by the following patch:

`--- Makefile.orig       2018-10-26 08:13:41.749524434 +0200
+++ Makefile    2018-10-26 08:14:11.566508520 +0200
@@ -3,7 +3,7 @@
 GETTEXT_PACKAGE = $(PACKAGE)
 UUID = netspeed@hedayaty.gmail.com

-LANGUAGES=de fa en_CA it fr pt_BR zh_CN zh_TW
+LANGUAGES=de fa en_CA es_ES it nl_NL fr pt_BR tr zh_CN zh_TW
 DOC_FILES=CHANGELOG README
 SRC_FILES=extension.js prefs.js layout_menu_item.js net_speed.js net_speed_status_icon.js
 MO_FILES=$(foreach LANGUAGE, $(LANGUAGES), locale/$(LANGUAGE)/LC_MESSAGES/$(GETTEXT_PACKAGE).mo)`

**Comment by hedayaty** [comment]
Done
