### ISSUE TITLE
gnome-desktop 3.32：not work

### ISSUE THREAD

**Issue by ChengBinH** [hedayaty/NetSpeed#88]
![Uploading image.png…](https://user-images.githubusercontent.com/29044591/54512298-b5746a80-498e-11e9-9ccf-9c321bc33f0e.png)
gnome-desktop3.32:not work 
Ubuntu19.04 development branch
![image](https://user-images.githubusercontent.com/29044591/54513137-61b75080-4991-11e9-8a19-54c4735e654b.png)

**Comment by ChengBinH** [comment]
![image](https://user-images.githubusercontent.com/29044591/54512298-b5746a80-498e-11e9-9ccf-9c321bc33f0e.png)

**Comment by mon0theist** [comment]
Can confirm, needs update for GNOME 3.32

**Comment by ChengBinH** [comment]
> 可以确认，需要更新GNOME 3.32

![image](https://user-images.githubusercontent.com/29044591/54572231-63305980-4a21-11e9-8674-8d3a919b2bc4.png)
I'm gnome3.32
